stableavailable: true
stableversion: 1.10.4
betaavailable: true
betaversion: 1.10.5b2
showversionwarning: false
minversionwarning: 1.9.0
showolderversions: true
usesuffix: false
buttonsstable:
    -
        prefix: win-x64
        icon: win10
        text: 'Windows 64-bit'
        extension: exe
    -
        prefix: osx-intel
        icon: apple
        text: 'Mac Intel'
        extension: pkg
    -
        prefix: osx-silicon
        icon: apple
        text: 'Mac Silicon'
        extension: pkg

    -   prefix: linux-x64
        icon: ubuntu
        text: 'Linux 64-bit'
        extension: AppImage

    -   prefix: linux-armhf
        icon: raspberry-pi
        text: 'Raspberry Pi / armv8'
        extension: AppImage

    -   prefix: linux-aarch64
        icon: raspberry-pi
        text: 'Raspberry Pi / aarch64'
        extension: AppImage

    -
        prefix: win7-x64
        icon: win10
        text: 'Windows 7 64-bit'
        extension: exe

buttonsbeta:
    -
        prefix: win-x64
        icon: win10
        text: 'Windows 64-bit'
        extension: exe
    -
        prefix: osx-intel
        icon: apple
        text: 'Mac Intel'
        extension: pkg
    -
        prefix: osx-silicon
        icon: apple
        text: 'Mac Silicon'
        extension: pkg
    -
        prefix: linux-x64
        icon: ubuntu
        text: 'Linux 64-bit'
        extension: AppImage

    -   prefix: linux-armhf
        icon: raspberry-pi
        text: 'Raspberry Pi / armv8'
        extension: AppImage

    -   prefix: linux-aarch64
        icon: raspberry-pi
        text: 'Raspberry Pi / aarch64'
        extension: AppImage

    -
        prefix: win7-x64
        icon: win10
        text: 'Windows 7 64-bit'
        extension: exe

buttonsbleeding:
    -
        prefix: win-x64
        icon: win10
        text: 'Windows 64-bit Bleeding Edge'
        extension: exe
    -
        prefix: osx-intel
        icon: apple
        text: 'Mac Intel Bleeding Edge'
        extension: pkg
    -
        prefix: osx-silicon
        icon: apple
        text: 'Mac Silicon Bleeding Edge'
        extension: pkg
    -
        prefix: linux-x64
        icon: ubuntu
        text: 'Linux 64-bit Bleeding Edge'
        extension: AppImage

    -   prefix: linux-armhf
        icon: raspberry-pi
        text: 'Raspberry Pi / armv8 Bleeding Edge'
        extension: AppImage

    -   prefix: linux-aarch64
        icon: raspberry-pi
        text: 'Raspberry Pi / aarch64 Bleeding Edge'
        extension: AppImage
    -
        prefix: win7-x64
        icon: win10
        text: 'Windows 7 64-bit Bleeding Edge'
        extension: exe

olderversionsstable:
    - 1.10.3
    - 1.10.2
    - 1.10.1
    - 1.10.0
    - 1.9.24
    - 1.9.23
    - 1.9.22
    - 1.9.20
    - 1.9.19
    - 1.9.18
    - 1.9.17
    - 1.9.16
    - 1.9.15
    - 1.9.14
    - 1.9.13
    - 1.9.12
    - 1.9.11
    - 1.9.10
    - 1.9.9
    - 1.9.8
    - 1.9.7
    - 1.9.6
    - 1.9.5
    - 1.9.4
    - 1.9.2
    - 1.9.1
    - 1.8.2
    - 1.8.1
    - 1.8.0
    - 1.7.6
    - 1.7.5
    - 1.7.4
    - 1.7.3
    - 1.7.2
    - 1.7.1
    - 1.7.0
    - 1.6.14
    - 1.6.13
    - 1.6.12
    - 1.6.11
    - 1.6.9
    - 1.6.8
    - 1.6.7
    - 1.6.6
    - 1.6.5
    - 1.6.4
    - 1.6.3
    - 1.6.2
    - 1.6.1
    - 1.6.0
    - 1.5.11
    - 1.5.10
    - 1.5.9
    - 1.5.8
    - 1.5.5
    - 1.5.4
    - 1.5.3
    - 1.5.2

olderversionsbeta:
    - 1.10.5b1
    - 1.10.4b6
    - 1.10.4b5
    - 1.10.4b4
    - 1.10.4b3
    - 1.10.4b2
    - 1.10.4b1
    - 1.10.2b3
    - 1.10.2b2
    - 1.10.2b1
    - 1.10.1b1
    - 1.9.25b13
    - 1.9.25b12
    - 1.9.25b11
    - 1.9.25b10
    - 1.9.25b9
    - 1.9.25b8
    - 1.9.25b7
    - 1.9.25b6
    - 1.9.25b5
    - 1.9.25b4
    - 1.9.25b3
    - 1.9.25b2
    - 1.9.25b1
    - 1.9.20b8
    - 1.9.20b7
    - 1.9.20b6
    - 1.9.20b5
    - 1.9.20b4
    - 1.9.20b3
    - 1.9.20b2
    - 1.9.20b1
    - 1.9.18b13
    - 1.9.18b12
    - 1.9.18b11
    - 1.9.18b10
    - 1.9.18b9
    - 1.9.18b8
    - 1.9.18b5
    - 1.9.18b4
    - 1.9.18b3
    - 1.9.18b2
    - 1.9.18b1
    - 1.9.17b12
    - 1.9.17b11
    - 1.9.17b10
    - 1.9.17b9
    - 1.9.17b8
    - 1.9.17b7
    - 1.9.17b6
    - 1.9.17b5
    - 1.9.17b4
    - 1.9.17b3
    - 1.9.17b2
    - 1.9.17b1
    - 1.9.16b2
    - 1.9.16b1
    - 1.9.15b4
    - 1.9.15b3
    - 1.9.15b2
    - 1.9.15b1
    - 1.9.14b12
    - 1.9.14b11
    - 1.9.14b10
    - 1.9.14b9
    - 1.9.14b8
    - 1.9.14b7
    - 1.9.14b6
    - 1.9.14b5
    - 1.9.14b4
    - 1.9.14b3
    - 1.9.14b2
    - 1.9.14b1
    - 1.9.13b1
    - 1.9.12b4
    - 1.9.12b3
    - 1.9.12b2
    - 1.9.12b1
    - 1.9.10b1
    - 1.9.9b7
    - 1.9.9b6
    - 1.9.9b5
    - 1.9.9b4
    - 1.9.9b3
    - 1.9.9b2
    - 1.9.9b1
    - 1.9.8b15
    - 1.9.8b14
    - 1.9.8b13
    - 1.9.8b12
    - 1.9.8b11
    - 1.9.8b10
    - 1.9.8b9
    - 1.9.8b8
    - 1.9.8b7
    - 1.9.8b6
    - 1.9.8b5
    - 1.9.8b4
    - 1.9.8b3
    - 1.9.8b2
    - 1.9.8b1
    - 1.9.7b20
    - 1.9.7b19
    - 1.9.7b18
    - 1.9.7b17
    - 1.9.7b16
    - 1.9.7b15
    - 1.9.7b14
    - 1.9.7b13
    - 1.9.7b12
    - 1.9.7b11
    - 1.9.7b10
    - 1.9.7b9
    - 1.9.7b8
    - 1.9.7b7
    - 1.9.7b6
    - 1.9.7b5
    - 1.9.7b4
    - 1.9.7b3
    - 1.9.7b2
    - 1.9.7b1
    - 1.9.5b31
    - 1.9.5b30
    - 1.9.5b28
    - 1.9.5b27
    - 1.9.5b26
    - 1.9.5b25
    - 1.9.5b24
    - 1.9.5b23
    - 1.9.5b22
    - 1.9.5b21
    - 1.9.5b20
    - 1.9.5b19
    - 1.9.5b18
    - 1.9.5b17
    - 1.9.5b16
    - 1.9.5b15
    - 1.9.5b14
    - 1.9.5b13
    - 1.9.5b12
    - 1.9.5b11
    - 1.9.5b10
    - 1.9.5b9
    - 1.9.5b8
    - 1.9.5b7
    - 1.9.5b6
    - 1.9.5b5
    - 1.9.5b4
    - 1.9.5b3
    - 1.9.4b1
    - 1.9.3b25
    - 1.9.3b24
    - 1.9.3b23
    - 1.9.3b22
    - 1.9.3b21
    - 1.9.3b20
    - 1.9.3b19
    - 1.9.3b18
    - 1.9.3b17
    - 1.9.3b16
    - 1.9.3b15
    - 1.9.3b14
    - 1.9.3b13
    - 1.9.3b12
    - 1.9.3b11
    - 1.9.3b10
    - 1.9.3b9
    - 1.9.3b8
    - 1.9.3b7
    - 1.9.3b6
    - 1.9.3b5
    - 1.9.3b4
    - 1.9.3b3
    - 1.9.3b2
    - 1.9.3b1
    - 1.9.1b22
    - 1.9.1b21
    - 1.9.1b20
    - 1.9.1b19
    - 1.9.1b18
    - 1.9.1b17
    - 1.9.1b16
    - 1.9.1b15
    - 1.9.1b14
    - 1.9.1b13
    - 1.9.1b12
    - 1.9.1b11
    - 1.9.1b10
    - 1.9.1b9
    - 1.9.1b8
    - 1.9.1b7
    - 1.9.1b6
    - 1.9.1b5
    - 1.9.1b4
    - 1.9.1b3
    - 1.9.1b2
    - 1.9.1b1
    - 1.9.0b6
    - 1.9.0b5
    - 1.9.0b4
    - 1.9.0b3
    - 1.9.0b2
    - 1.9.0b1
    - 1.8.3b7
    - 1.8.3b6
    - 1.8.3b5
    - 1.8.3b4
    - 1.8.3b3
    - 1.8.3b2
    - 1.8.3b1
    - 1.8.1b0
    - 1.8.1b9
    - 1.8.1b8
    - 1.8.1b7
    - 1.8.1b6
    - 1.8.1b5
    - 1.8.1b4
    - 1.8.1b3
    - 1.8.1b2
    - 1.8.1b1
    - 1.8.0b44
    - 1.8.0b43
    - 1.8.0b42
    - 1.8.0b41
    - 1.8.0b40
    - 1.8.0b39
    - 1.8.0b38
    - 1.8.0b37
    - 1.8.0b36
    - 1.8.0b35
    - 1.8.0b34
    - 1.8.0b33
    - 1.8.0b32
    - 1.8.0b31
    - 1.8.0b30
    - 1.8.0b29
    - 1.8.0b28
    - 1.8.0b27
    - 1.8.0b26
    - 1.8.0b25
    - 1.8.0b24
    - 1.8.0b23
    - 1.8.0b22
    - 1.8.0b21
    - 1.8.0b20
    - 1.8.0b19
    - 1.8.0b18
    - 1.8.0b17
    - 1.8.0b16
    - 1.8.0b15
    - 1.8.0b14
    - 1.8.0b13
    - 1.8.0b12
    - 1.8.0b11
    - 1.8.0b10
    - 1.8.0b9
    - 1.8.0b8
    - 1.8.0b7
    - 1.8.0b6
    - 1.8.0b5
    - 1.8.0b4
    - 1.8.0b3
    - 1.8.0b2
    - 1.8.0b1
    - 1.7.7b7
    - 1.7.7b6
    - 1.7.7b5
    - 1.7.7b4
    - 1.7.7b3
    - 1.7.7b2
    - 1.7.7b1
    - 1.7.6b1
    - 1.7.5b21
    - 1.7.5b20
    - 1.7.5b19
    - 1.7.5b18
    - 1.7.5b17
    - 1.7.5b16
    - 1.7.5b15
    - 1.7.5b14
    - 1.7.5b13
    - 1.7.5b12
    - 1.7.5b11
    - 1.7.5b10
    - 1.7.5b9
    - 1.7.5b8
    - 1.7.5b7
    - 1.7.5b6
    - 1.7.5b5
    - 1.7.5b4
    - 1.7.5b3
    - 1.7.5b2
    - 1.7.5b1
    - 1.7.0b32
    - 1.7.0b31
    - 1.7.0b30
    - 1.7.0b29
    - 1.7.0b28
    - 1.7.0b27
    - 1.7.0b26
    - 1.7.0b25
    - 1.7.0b24
    - 1.7.0b23
    - 1.7.0b22
    - 1.7.0b21
    - 1.7.0b20
    - 1.7.0b19
    - 1.7.0b18
    - 1.7.0b17
    - 1.7.0b16
    - 1.7.0b15
    - 1.7.0b14
    - 1.7.0b13
    - 1.7.0b12
    - 1.7.0b11
    - 1.7.0b10
    - 1.7.0b9
    - 1.7.0b8
    - 1.7.0b7
    - 1.7.0b5
    - 1.7.0b4
    - 1.7.0b3
    - 1.7.0b2
    - 1.7.0b1
    - 1.6.13b13
    - 1.6.13b11
    - 1.6.13b9
    - 1.6.13b8
    - 1.6.13b7
    - 1.6.13b6
    - 1.6.13b5
    - 1.6.13b4
    - 1.6.13b3
    - 1.6.13b2
    - 1.6.13b1
    - 1.6.12b6
    - 1.6.12b5
    - 1.6.12b4
    - 1.6.12b3
    - 1.6.12b2
    - 1.6.12b1
    - 1.6.10b4
    - 1.6.10b3
    - 1.6.10b2
    - 1.6.10b1
    - 1.6.9b4
    - 1.6.9b3
    - 1.6.9b2
    - 1.6.9b1
    - 1.6.6b6
    - 1.6.6b5
    - 1.6.6b4
    - 1.6.6b3
    - 1.6.6b2
    - 1.6.6b1
    - 1.6.5b14
    - 1.6.5b13
    - 1.6.5b12
    - 1.6.5b10
    - 1.6.5b8
    - 1.6.5b7
    - 1.6.5b6
    - 1.6.5b5
    - 1.6.5b4
    - 1.6.5b3
    - 1.6.5b2
    - 1.6.5b1
    - 1.6.4b9
    - 1.6.4b7
    - 1.6.4b6
    - 1.6.4b5
    - 1.6.4b4
    - 1.6.4b3
    - 1.6.4b2
    - 1.6.4b1
    - 1.6.3b10
    - 1.6.3b9
    - 1.6.3b8
    - 1.6.3b7
    - 1.6.3b6
    - 1.6.3b5
    - 1.6.3b4
    - 1.6.3b3
    - 1.6.3b2
    - 1.6.3b1
    - 1.6.2b7
    - 1.6.2b6
    - 1.6.2b5
    - 1.6.2b4
    - 1.6.2b3
    - 1.6.2b2
    - 1.6.2b1
    - 1.6.1b4
    - 1.6.1b3
    - 1.6.1b2
    - 1.6.1b1
    - 1.6.0b11
    - 1.6.0b10
    - 1.6.0b9
    - 1.6.0b8
    - 1.6.0b7
    - 1.6.0b6
    - 1.6.0b5
    - 1.6.0b4
    - 1.6.0b3
    - 1.6.0b2
    - 1.6.0b1
    - 1.5.11b3
    - 1.5.11b2
    - 1.5.11b1
    - 1.5.9b9
    - 1.5.9b8
    - 1.5.9b7
    - 1.5.9b6
    - 1.5.9b5
    - 1.5.9b4
    - 1.5.9b3
    - 1.5.9b2
    - 1.5.9b1
    - 1.5.8b3
    - 1.5.8b1
    - 1.5.4b1
    - 1.5.3b3
    - 1.5.3b2
    - 1.5.3b1
    - 1.5.1-stable
    - 1.5.1b-beta
    - 1.5.0b-beta
    - 1.4.15-stable
    - 1.4.14-stable
    - 1.4.13-stable
    - 1.4.12-stable
    - 1.4.12b-beta
    - 1.4.11-stable
    - 1.4.10-stable
    - 1.4.9-stable
    - 1.4.8-stable
    - 1.4.5-stable
    - 1.4.4-stable
    - 1.4.3-stable
    - 1.4.2-stable
    - 1.4.1-stable
    - 1.4.0-stable
    - 1.4.0b-beta
