# Debian 11 image prepared for Chataigne build
FROM debian:bullseye

# Install build dependencies and tools
RUN apt-get update
RUN apt-get install -qyf \
        wget \
        curl \
        libcurl3-gnutls \
        libfreetype6-dev \
        libx11-dev \
        libxinerama-dev \
        libxrandr-dev \
        libxcursor-dev \
        libxcomposite-dev \
        mesa-common-dev \
        libasound2-dev \
        freeglut3-dev \
        libcurl4-gnutls-dev \
        libasound2-dev \
        libjack-dev \
        libbluetooth-dev \
        libgtk-3-dev \
        libwebkit2gtk-4.0-dev \
        libsdl2-dev \
        libfuse2 \
        libusb-1.0-0-dev \
        libhidapi-dev \
        ladspa-sdk